---
- hosts: all
  become: true
  vars_files:
    - secrets.yml
  vars:
    vault_identity_list: ['./secrets.yml']
    vault_password_file: './vault-password-file'
  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    # Install Java
    - name: Install Java
      apt:
        name: default-jdk
        state: present
        update_cache: yes
    
    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    # Start the Jenkins service
    - name: Start the Jenkins service
      service:
        name: jenkins
        state: started
        enabled: true

    # Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
    
    - name: Enable Docker service
      service:
        name: docker
        enabled: true

    # Install Azure CLI
    - name: Install Azure CLI
      pip:
        name: azure-cli
        state: latest
    
    - name: Authenticate Azure CLI
      shell: |
        az login --service-principal -u {{ AZURE_CLIENT_ID }} -p {{AZURE_CLIENT_SECRET}} --tenant {{AZURE_TENANT_ID}}
        az account set --subscription {{AZURE_SUBSCRIPTION_ID}}
