apiVersion: apps/v1
kind: Deployment
metadata:
  name: esr-todolist
  labels:
    app: esr-todolist

spec:
  replicas: 2
  selector:
    matchLabels:
      app: esr-todolist
  template:
    metadata:
      labels:
        app: esr-todolist
    spec:
      containers:
      - name: esr-todolist
        image: acr-prod.azurecr.io/esr-todolist:latest
        ports:
        - containerPort: 8080
          name: todolist-port