apiVersion: v1
kind: Service
metadata:
  name: todolist-loadbalancer
  labels:
    app: esr-todolist

spec:
  selector:
    app: todolist
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: todolist-port
      protocol: TCP
  selector:
    app: esr-todolist
    