apiVersion: v1
kind: Service
metadata:
  name: todolist-loadbalancer
  namespace: development
spec:
  selector:
    app: todolist
  ports:
    - port: 80
      targetPort: todolist-port
      nodePort: 30001
  type: LoadBalancer